### ISSUE TITLE
Rewrite persistence layer

### ISSUE THREAD

**Issue by C5247714** [linden-honey/linden-honey#8]
* try to use [Sequelize](http://docs.sequelizejs.com)
* rewrite models
* rewrite migration script
* rewrite controllers add support for all levels of hierarchy (except recursion) and add queries support

**Comment by alebabai** [comment]
![](http://i3.kym-cdn.com/entries/icons/original/000/007/423/untitle.JPG)
Mongo and Mongoose one love!
